"use client";

import {
	AlertTriangle,
	ArrowRight,
	ChevronDown,
	Circle,
	FileText,
} from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useCallback, useEffect, useRef, useState } from "react";
import type { TaskTree } from "@/lib/services/task-service";
import { cn } from "@/lib/utils";
import { useChatStore, useUIStore } from "@/store";
import { ImplementationOptions } from "./implementation-options";
import { WhiteboardCanvas } from "./whiteboard-canvas";

interface TaskDetailProps {
	projectId: string;
	projectName: string;
	taskTree: TaskTree | null;
	hasAc: boolean;
	taskStatus?: string | null;
}

/**
 * Task detail container - orchestrates generate flow, canvas, mobile fallback.
 */
export function TaskDetail({
	projectId,
	projectName,
	taskTree,
	hasAc,
	taskStatus,
}: TaskDetailProps) {
	const router = useRouter();
	const showToast = useUIStore((s) => s.showToast);
	const setTaskGenerated = useChatStore((s) => s.setTaskGenerated);

	// Sync store flag from server-loaded status on mount/project switch, avoids
	// stale true/false leaking across different projects' Task pages.
	useEffect(() => {
		setTaskGenerated(taskStatus === "completed");
	}, [projectId, taskStatus, setTaskGenerated]);

	// Init true when no tasks yet, prevents flash of empty state before useEffect fires
	const [isGenerating, setIsGenerating] = useState(() => !taskTree && hasAc);
	const [thinkingText, setThinkingText] = useState("");
	const [hasError, setHasError] = useState(false);
	const [generatedTaskTree, setGeneratedTaskTree] = useState<TaskTree | null>(
		null,
	);
	const [revealCount, setRevealCount] = useState<number | null>(null);
	const isGeneratingRef = useRef(false);
	const abortRef = useRef<AbortController | null>(null);
	const staggerRef = useRef<ReturnType<typeof setInterval> | null>(null);
	const hasAutoGenerated = useRef(false);

	// Abort in-flight generation on unmount/project switch. Also resets
	// hasAutoGenerated so StrictMode's dev-mode phantom unmount->remount cycle
	// retries the aborted fetch instead of leaving it dead (ac-detail.tsx uses
	// the same pattern - see comment there for why the ref must be reset here).
	useEffect(() => {
		return () => {
			abortRef.current?.abort();
			abortRef.current = null;
			isGeneratingRef.current = false;
			hasAutoGenerated.current = false;
			if (staggerRef.current) clearInterval(staggerRef.current);
		};
	}, [projectId]);

	const handleGenerate = useCallback(async () => {
		if (isGeneratingRef.current) return;
		if (!hasAc) {
			showToast("AC belum tersedia. Generate AC terlebih dahulu.", "error");
			return;
		}

		isGeneratingRef.current = true;
		setIsGenerating(true);
		setThinkingText("");
		setHasError(false);

		abortRef.current?.abort();
		const controller = new AbortController();
		abortRef.current = controller;

		try {
			const response = await fetch("/api/task/generate", {
				method: "POST",
				headers: { "Content-Type": "application/json" },
				body: JSON.stringify({
					projectId,
					model: sessionStorage.getItem("novaplan:selected-model") || undefined,
				}),
				signal: controller.signal,
			});

			if (!response.ok) {
				const error = await response.json();
				if (response.status === 403 && error.code === "UPGRADE_REQUIRED") {
					showToast(
						"Generate Task hanya tersedia di paket Pro dan Hengker.",
						"error",
					);
					router.push("/pricing");
					return;
				}
				throw new Error(error.error || "Gagal generate");
			}

			const reader = response.body?.getReader();
			if (!reader) throw new Error("No reader");

			const decoder = new TextDecoder();
			let buffer = "";

			while (true) {
				const { done, value } = await reader.read();
				if (done) break;

				buffer += decoder.decode(value, { stream: true });
				const lines = buffer.split("\n");
				buffer = lines.pop() || "";

				for (const line of lines) {
					if (!line.startsWith("data: ")) continue;
					try {
						const data = JSON.parse(line.slice(6));
						if (data.type === "thinking") {
							setThinkingText((prev) => prev + data.content);
						} else if (data.type === "delta") {
							if (thinkingText) setThinkingText("");
							// ponytail: delta content not displayed, skeleton shown instead
						} else if (data.type === "done") {
							const tree = data.taskTree as TaskTree;
							setGeneratedTaskTree(tree);
							setRevealCount(0);
							let count = 0;
							if (staggerRef.current) clearInterval(staggerRef.current);
							staggerRef.current = setInterval(() => {
								count++;
								setRevealCount(count);
								if (count >= tree.features.length) {
									if (staggerRef.current) clearInterval(staggerRef.current);
									staggerRef.current = null;
									setRevealCount(null);
								}
							}, 300);
							setTaskGenerated(true);
							showToast("Task tree berhasil digenerate!", "success");
						} else if (data.type === "error") {
							setHasError(true);
							showToast(data.error || "Gagal generate", "error");
						}
					} catch {
						console.warn("SSE parse failed:", line.slice(0, 80));
					}
				}
			}
		} catch (error: unknown) {
			if (error instanceof DOMException && error.name === "AbortError") {
				// A newer handleGenerate call already superseded this one (see abortRef.current?.abort()
				// above) - that call owns isGenerating state now, so don't stomp on it.
				if (abortRef.current !== controller) return;
				isGeneratingRef.current = false;
				setIsGenerating(false);
				return;
			}
			console.error("Generate task error:", error);
			showToast(
				error instanceof Error ? error.message : "Gagal generate task",
				"error",
			);
			setHasError(true);
			isGeneratingRef.current = false;
			setIsGenerating(false);
			abortRef.current = null;
			return;
		}
		isGeneratingRef.current = false;
		setIsGenerating(false);
		abortRef.current = null;
	}, [hasAc, projectId, showToast]);

	// Auto-generate on mount if no tasks yet.
	// Uses ref to access latest handleGenerate, avoiding stale closure issue.
	const handleGenerateRef = useRef(handleGenerate);
	handleGenerateRef.current = handleGenerate;

	useEffect(() => {
		if (taskTree || hasAutoGenerated.current) return;
		hasAutoGenerated.current = true;
		handleGenerateRef.current();
	}, [taskTree]);

	// No AC state
	if (!hasAc) {
		return (
			<div className="flex h-full items-center justify-center bg-onyx text-snow">
				<div className="text-center">
					<FileText size={64} className="mx-auto mb-4 text-fog" />
					<h2 className="mb-2 text-xl font-[510]">AC Belum Tersedia</h2>
					<p className="mb-6 text-fog">
						Generate Acceptance Criteria terlebih dahulu.
					</p>
					<Link
						href={`/ac/${projectId}`}
						className="btn-primary inline-flex items-center gap-2 rounded-md px-4 py-2"
					>
						<ArrowRight size={16} />
						Ke AC
					</Link>
				</div>
			</div>
		);
	}

	const currentTaskTree = generatedTaskTree ?? taskTree;
	const visibleTaskTree =
		currentTaskTree && revealCount !== null
			? { features: currentTaskTree.features.slice(0, revealCount) }
			: currentTaskTree;
	const hasContent = Boolean(
		visibleTaskTree && visibleTaskTree.features.length > 0,
	);

	// Title: show loading text during streaming, project name when done
	const displayTitle = isGenerating ? "Menyusun task tree..." : projectName;

	return (
		<div className="flex h-full flex-col bg-onyx text-snow">
			{/* Topbar */}
			<div className="flex items-center justify-between border-b border-graphite bg-obsidian px-4 py-3">
				<h1
					className={cn(
						"truncate font-inter text-lg font-[510]",
						isGenerating && "animate-pulse text-fog",
					)}
				>
					{displayTitle}
				</h1>
				<div className="flex items-center gap-3">
					<Link
						href={`/kanban/${projectId}`}
						className="btn-primary px-3 py-1.5 rounded-md text-xs font-[510]"
					>
						Task
					</Link>
					<ImplementationOptions
						projectId={projectId}
						projectName={projectName}
						hasContent={hasContent}
					/>
				</div>
			</div>

			{/* Canvas / generate */}
			{isGenerating && thinkingText && !currentTaskTree && (
				<details
					className="text-xs text-fog/60 px-4 py-2 border-b border-graphite/40"
					open
				>
					<summary className="cursor-pointer select-none">
						AI sedang berpikir...
					</summary>
					<pre className="mt-1 whitespace-pre-wrap text-xs text-fog/40 max-h-40 overflow-y-auto custom-scrollbar">
						{thinkingText}
					</pre>
				</details>
			)}
			<div className="relative flex-1 overflow-hidden">
				{/* Mobile: stacked accordion <md */}
				{visibleTaskTree && hasContent && (
					<div
						className="h-full overflow-y-auto md:hidden"
						style={{ overscrollBehavior: "contain" }}
					>
						<div className="space-y-3 p-3">
							{visibleTaskTree.features.map((feature, fi) => (
								<details
									key={fi}
									className="rounded-lg border border-graphite bg-obsidian"
								>
									<summary
										className="flex cursor-pointer items-center gap-2 px-3 py-2 font-inter text-sm font-[510]"
										style={{
											borderLeft: `3px solid ${["#6366f1", "#10b981", "#f59e0b", "#ef4444", "#8b5cf6", "#ec4899", "#06b6d4", "#84cc16", "#f97316", "#14b8a6"][fi % 10]}`,
										}}
									>
										<ChevronDown size={14} /> {feature.name}
									</summary>
									<div className="border-t border-graphite px-3 py-2">
										{!feature.tasks || feature.tasks.length === 0 ? (
											<p className="text-xs text-fog italic">Tidak ada task</p>
										) : (
											<ul className="space-y-2">
												{feature.tasks.map((task, ti) => (
													<li key={ti}>
														<p className="text-sm font-[510] text-snow">
															{task.name}
														</p>
														{task.subtasks && task.subtasks.length > 0 && (
															<ul className="mt-1 space-y-1 pl-3">
																{task.subtasks.map((sub, si) => (
																	<li key={si} className="text-xs text-fog">
																		<div className="flex items-center gap-1.5">
																			<Circle
																				size={5}
																				className="shrink-0 fill-fog/40"
																			/>{" "}
																			{sub.name}
																		</div>
																		{sub.details && sub.details.length > 0 && (
																			<ul className="mt-0.5 space-y-0.5 pl-4">
																				{sub.details.map((detail, di) => (
																					<li
																						key={di}
																						className="text-[11px] text-fog/70"
																					>
																						– {detail}
																					</li>
																				))}
																			</ul>
																		)}
																	</li>
																))}
															</ul>
														)}
													</li>
												))}
											</ul>
										)}
									</div>
								</details>
							))}
						</div>
					</div>
				)}

				{/* Desktop: interactive canvas >md */}
				<div className={cn("h-full", hasContent && "hidden md:block")}>
					{hasError && !isGenerating && !hasContent ? (
						<div className="flex h-full flex-col items-center justify-center gap-3 text-center">
							<AlertTriangle size={40} className="text-crimson" />
							<p className="text-fog">Gagal generate task tree.</p>
							<button
								onClick={() => handleGenerate()}
								className="btn-primary rounded-md px-4 py-2 text-sm"
							>
								Coba Lagi
							</button>
						</div>
					) : (
						<WhiteboardCanvas
							projectName={projectName}
							taskTree={visibleTaskTree}
						/>
					)}
				</div>
			</div>
		</div>
	);
}
