"use client";

import { useState, useRef, useEffect, useCallback } from "react";
import { useRouter } from "next/navigation";
import { WhiteboardCanvas } from "./whiteboard-canvas";
import { TabBar, type TaskTab } from "./tab-bar";
import { useUIStore } from "@/store";
import type { TaskTree } from "@/lib/services/task-service";
import type { SitemapTree, SitemapPage } from "@/lib/services/sitemap-service";
import { ImplementationOptions } from "./implementation-options";
import { Sparkles, FileText, ArrowRight, ChevronDown, Circle, Lock, Globe } from "lucide-react";
import { cn } from "@/lib/utils";
import Link from "next/link";

interface TaskDetailProps {
  projectId: string;
  projectName: string;
  taskTree: TaskTree | null;
  hasAc: boolean;
  initialSitemapTree?: SitemapTree | null;
}

type GenerateKind = "task" | "sitemap";

/**
 * Task detail container — orchestrates generate flow (task + sitemap), canvas,
 * tab bar, mobile fallback. Flow Step Nav step 3 active via routeToStep (PRD-02).
 */
export function TaskDetail({ projectId, projectName, taskTree, hasAc, initialSitemapTree = null }: TaskDetailProps) {
  const router = useRouter();
  const showToast = useUIStore((s) => s.showToast);

  const [activeTab, setActiveTab] = useState<TaskTab>("board");
  const handleTabChange = useCallback((tab: TaskTab) => {
    // Abort any in-flight generation when switching tabs.
    abortRef.current?.abort();
    abortRef.current = null;
    setActiveTab(tab);
  }, []);
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatingKind, setGeneratingKind] = useState<GenerateKind>("task");
  const [streamingContent, setStreamingContent] = useState("");
  const [generatedTaskTree, setGeneratedTaskTree] = useState<TaskTree | null>(null);
  const [sitemapTree, setSitemapTree] = useState<SitemapTree | null>(initialSitemapTree);
  // ponytail: synchronous double-click guard — state updates are async.
  const isGeneratingRef = useRef(false);
  const abortRef = useRef<AbortController | null>(null);

  // Abort any in-flight generation on unmount / project switch.
  useEffect(() => {
    return () => {
      abortRef.current?.abort();
      abortRef.current = null;
    };
  }, [projectId]);

  // Auto-generate task tree on arrival if no tasks exist yet.
  const hasAutoGenerated = useRef(false);
  useEffect(() => {
    if (!hasAc || taskTree || hasAutoGenerated.current || isGenerating) return;
    hasAutoGenerated.current = true;
    handleGenerate();
  }, [hasAc, taskTree, isGenerating]);

  const streamGenerate = useCallback(
    async (kind: GenerateKind) => {
      if (isGeneratingRef.current) return;
      if (!hasAc) {
        showToast("AC belum tersedia. Generate AC terlebih dahulu.", "error");
        return;
      }

      isGeneratingRef.current = true;
      setIsGenerating(true);
      setGeneratingKind(kind);
      setStreamingContent("");

      abortRef.current?.abort();
      const controller = new AbortController();
      abortRef.current = controller;

      const endpoint = kind === "task" ? "/api/task/generate" : "/api/sitemap/generate";

      try {
        const response = await fetch(endpoint, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ projectId }),
          signal: controller.signal,
        });

        if (!response.ok) {
          const error = await response.json();
          throw new Error(error.error || "Gagal generate");
        }

        const reader = response.body?.getReader();
        if (!reader) throw new Error("No reader");

        const decoder = new TextDecoder();
        let buffer = "";

        while (true) {
          const { done, value } = await reader.read();
          if (done) break;

          buffer += decoder.decode(value, { stream: true });
          const lines = buffer.split("\n");
          buffer = lines.pop() || "";

          for (const line of lines) {
            if (!line.startsWith("data: ")) continue;
            try {
              const data = JSON.parse(line.slice(6));
              if (data.type === "delta") {
                setStreamingContent((prev) => prev + data.content);
              } else if (data.type === "done") {
                if (kind === "task") {
                  setGeneratedTaskTree(data.taskTree);
                } else {
                  setSitemapTree(data.sitemapTree);
                }
                showToast(
                  kind === "task" ? "Task tree berhasil digenerate!" : "Sitemap berhasil digenerate!",
                  "success",
                );
              } else if (data.type === "error") {
                showToast(data.error || "Gagal generate", "error");
              }
            } catch {
              console.warn("SSE parse failed:", line.slice(0, 80));
            }
          }
        }

        router.refresh();
      } catch (error: unknown) {
        if (error instanceof DOMException && error.name === "AbortError") {
          return;
        }
        console.error(`Generate ${kind} error:`, error);
        showToast(error instanceof Error ? error.message : `Gagal generate ${kind}`, "error");
      } finally {
        isGeneratingRef.current = false;
        setIsGenerating(false);
        setStreamingContent("");
        abortRef.current = null;
      }
    },
    [hasAc, projectId, router, showToast],
  );

  const handleGenerate = useCallback(() => {
    const kind: GenerateKind = activeTab === "board" ? "task" : "sitemap";
    streamGenerate(kind);
  }, [activeTab, streamGenerate]);

  // No AC state
  if (!hasAc) {
    return (
      <div className="flex h-dvh items-center justify-center bg-onyx text-snow">
        <div className="text-center">
          <FileText size={64} className="mx-auto mb-4 text-fog" />
          <h2 className="mb-2 text-xl font-[510]">AC Belum Tersedia</h2>
          <p className="mb-6 text-fog">Generate Acceptance Criteria terlebih dahulu.</p>
          <Link
            href={`/ac/${projectId}`}
            className="btn-primary inline-flex items-center gap-2 rounded-md px-4 py-2"
          >
            <ArrowRight size={16} />
            Ke AC
          </Link>
        </div>
      </div>
    );
  }

  const currentTaskTree = generatedTaskTree ?? taskTree;
  const currentSitemapTree = (sitemapTree ?? initialSitemapTree) ?? null;
  const isSitemapMode = activeTab === "sitemap";
  const showStream = isGenerating && streamingContent.length > 0;

  const taskHasContent = Boolean(currentTaskTree) || (isGenerating && generatingKind === "task" && showStream);
  const sitemapHasContent = Boolean(currentSitemapTree) || (isGenerating && generatingKind === "sitemap" && showStream);
  const hasContentForActiveTab = isSitemapMode ? sitemapHasContent : taskHasContent;

  return (
    <div className="flex h-dvh flex-col bg-onyx text-snow">
      {/* Topbar */}
      <div className="flex items-center justify-between border-b border-graphite bg-obsidian px-4 py-3">
        <h1 className="truncate font-inter text-lg font-[510]">{projectName}</h1>
        <div className="flex items-center gap-3">
          <TabBar active={activeTab} onChange={handleTabChange} sitemapEnabled />
          <ImplementationOptions
            projectId={projectId}
            projectName={projectName}
            hasContent={taskHasContent || sitemapHasContent}
          />
        </div>
      </div>

      {/* Canvas / generate */}
      <div className="relative flex-1 overflow-hidden">
        {/* Mobile: stacked accordion <md — task */}
        {currentTaskTree && !isSitemapMode && hasContentForActiveTab && (
          <div className="h-full overflow-y-auto md:hidden" style={{ overscrollBehavior: "contain" }}>
            <div className="space-y-3 p-3">
              {currentTaskTree.features.map((feature, fi) => (
                <details key={fi} className="rounded-lg border border-graphite bg-obsidian">
                  <summary className="flex cursor-pointer items-center gap-2 px-3 py-2 font-inter text-sm font-[510]"
                    style={{ borderLeft: `3px solid ${["#6366f1","#10b981","#f59e0b","#ef4444","#8b5cf6","#ec4899","#06b6d4","#84cc16","#f97316","#14b8a6"][fi % 10]}` }}
                  >
                    <ChevronDown size={14} /> {feature.name}
                  </summary>
                  <div className="border-t border-graphite px-3 py-2">
                    {(!feature.tasks || feature.tasks.length === 0) ? (
                      <p className="text-xs text-fog italic">Tidak ada task</p>
                    ) : (
                      <ul className="space-y-2">
                        {feature.tasks.map((task, ti) => (
                          <li key={ti}>
                            <p className="text-sm font-[510] text-snow">{task.name}</p>
                            {task.subtasks && task.subtasks.length > 0 && (
                              <ul className="mt-1 space-y-0.5 pl-3">
                                {task.subtasks.map((sub, si) => (
                                  <li key={si} className="flex items-center gap-1.5 text-xs text-fog">
                                    <Circle size={5} className="shrink-0 fill-fog/40" /> {sub.name}
                                  </li>
                                ))}
                              </ul>
                            )}
                          </li>
                        ))}
                      </ul>
                    )}
                  </div>
                </details>
              ))}
            </div>
          </div>
        )}

        {/* Mobile: nested list for sitemap <md */}
        {currentSitemapTree && isSitemapMode && (
          <div className="h-full overflow-y-auto md:hidden p-3" style={{ overscrollBehavior: "contain" }}>
            <SitemapMobileTree pages={currentSitemapTree.pages} depth={0} />
          </div>
        )}

        {/* Desktop: interactive canvas >md */}
        <div className={cn("h-full", (currentTaskTree && !isSitemapMode || currentSitemapTree && isSitemapMode) && hasContentForActiveTab && "hidden md:block")}>
          {hasContentForActiveTab ? (
            <WhiteboardCanvas
              mode={isSitemapMode ? "sitemap" : "task"}
              taskTree={isSitemapMode ? null : currentTaskTree}
              sitemapTree={isSitemapMode ? currentSitemapTree : null}
              isStreaming={isGenerating}
              streamingContent={streamingContent}
            />
          ) : (
            <div className="flex h-full items-center justify-center">
              <button
                type="button"
                onClick={handleGenerate}
                disabled={isGenerating}
                className="btn-primary flex items-center gap-2 rounded-md px-6 py-3 font-[510] disabled:opacity-40"
              >
                <Sparkles size={18} />
                {isSitemapMode ? "Generate Sitemap" : "Generate Task Tree"}
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

/** Recursive sitemap tree for mobile — indented nested list with auth badges. */
function SitemapMobileTree({ pages, depth }: { pages: SitemapPage[]; depth: number }) {
  return (
    <ul className="space-y-1" style={{ paddingLeft: depth * 16 }}>
      {pages.map((page, i) => (
        <li key={i}>
          <div className="flex items-center gap-2 rounded px-2 py-1.5 hover:bg-white/5">
            {page.isAuthRequired ? <Lock size={12} className="shrink-0 text-indigo" /> : <Globe size={12} className="shrink-0 text-emerald" />}
            <span className="text-sm text-snow">{page.name}</span>
            <code className="text-[10px] text-fog/60">/{page.path}</code>
          </div>
          {page.children.length > 0 && <SitemapMobileTree pages={page.children} depth={depth + 1} />}
        </li>
      ))}
    </ul>
  );
}
