"use client";

import { useState, useEffect, useRef, useCallback } from "react";
import { useRouter } from "next/navigation";
import { AcViewer } from "./ac-viewer";
import { TableOfContents } from "@/components/prd/table-of-contents";
import { usePanelResize } from "@/hooks/use-panel-resize";
import { useUIStore, useChatStore } from "@/store";
import type { AcVersion, Plan } from "@/types/database";
import { FileText, ArrowRight } from "lucide-react";
import Link from "next/link";
import { cn } from "@/lib/utils";

interface AcDetailProps {
  projectId: string;
  projectName: string;
  latestAcVersion?: AcVersion;
  latestPrdContent?: string;
  plan?: Plan;
}

export function AcDetail({
  projectId,
  projectName,
  latestAcVersion,
  latestPrdContent,
  plan = "free",
}: AcDetailProps) {
  const router = useRouter();
  const showToast = useUIStore((s) => s.showToast);
  const setGeneratingAC = useChatStore((s) => s.setGeneratingAC);
  const { leftWidth, onStartDragLeft, isDraggingLeft } = usePanelResize();

  const [isGenerating, setIsGenerating] = useState(false);
  const [streamingContent, setStreamingContent] = useState<string>("");
  const [hasError, setHasError] = useState(false);
  const hasAutoGenerated = useRef(false);
  const abortRef = useRef<AbortController | null>(null);

  const acContent = latestAcVersion?.content || null;

  const handleGenerate = useCallback(async () => {
    if (!latestPrdContent) {
      showToast("PRD belum tersedia. Generate PRD terlebih dahulu.", "error");
      return;
    }
    setIsGenerating(true);
    setGeneratingAC(true);
    setStreamingContent("");
    setHasError(false);

    abortRef.current?.abort();
    const controller = new AbortController();
    abortRef.current = controller;

    try {
      const response = await fetch("/api/ac/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ projectId }),
        signal: controller.signal,
      });
      if (!response.ok) {
        const error = await response.json();
        throw new Error(error.error || "Failed to generate AC");
      }
      const reader = response.body?.getReader();
      if (!reader) throw new Error("No reader available");
      const decoder = new TextDecoder();
      let buffer = "";
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split("\n");
        buffer = lines.pop() || "";
        for (const line of lines) {
          if (line.startsWith("data: ")) {
            try {
              const data = JSON.parse(line.slice(6));
              if (data.type === "delta") {
                setStreamingContent((prev) => prev + data.content);
              } else if (data.type === "done") {
                router.refresh();
                showToast("Acceptance Criteria berhasil digenerate!", "success");
                setIsGenerating(false);
                setGeneratingAC(false);
              } else if (data.type === "error") {
                setHasError(true);
                setIsGenerating(false);
                setGeneratingAC(false);
                showToast(data.error || "Gagal generate AC", "error");
              }
            } catch { /* skip malformed SSE line */ }
          }
        }
      }
      // Stream closed without a done/error event — clear flags so UI doesn't stick.
      setIsGenerating(false);
      setGeneratingAC(false);
    } catch (error: unknown) {
      const isAbort = (error instanceof DOMException || error instanceof Error) && error.name === "AbortError";
      if (isAbort) {
        // A newer handleGenerate call already superseded this one (see abortRef.current?.abort()
        // above) — that call owns isGenerating/error state now, so don't stomp on it.
        if (abortRef.current !== controller) return;
        showToast("Generate AC dibatalkan (timeout). Klik Generate ulang.", "error");
        setHasError(true);
        setIsGenerating(false);
        setGeneratingAC(false);
        return;
      }
      console.error("Generate AC error:", error);
      const msg = error instanceof Error ? error.message : "Gagal generate AC";
      showToast(msg, "error");
      setHasError(true);
      setIsGenerating(false);
      setGeneratingAC(false);
    }
  }, [projectId, latestPrdContent, showToast, router, setGeneratingAC]);

  // Auto-generate AC on first visit
  useEffect(() => {
    if (!latestPrdContent || latestAcVersion || hasAutoGenerated.current || isGenerating) return;
    hasAutoGenerated.current = true;
    handleGenerate();
    // ponytail: auto-gen once per mount; ref guard prevents re-run when handleGenerate ref changes
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [latestPrdContent, latestAcVersion, handleGenerate]);

  // Abort in-flight generation on unmount/project switch only — kept as a
  // separate effect (not the trigger effect's cleanup). Also resets
  // hasAutoGenerated so StrictMode's dev-mode phantom unmount->remount cycle
  // retries the aborted fetch instead of leaving it dead (the ref survives
  // the phantom cycle and would otherwise permanently block the retry).
  useEffect(() => {
    return () => {
      abortRef.current?.abort();
      hasAutoGenerated.current = false;
      setGeneratingAC(false);
    };
  }, [projectId, setGeneratingAC]);

  if (!latestPrdContent) {
    return (
      <div className="flex h-dvh items-center justify-center bg-onyx text-(--text-primary)">
        <div className="text-center">
          <FileText size={64} className="mx-auto mb-4 text-(--text-secondary)" />
          <h2 className="mb-2 text-xl font-[510] text-(--text-primary)">PRD Belum Tersedia</h2>
          <p className="mb-6 text-(--text-secondary)">Generate PRD terlebih dahulu sebelum membuat Acceptance Criteria.</p>
          <Link href={`/prd/${projectId}`} className="btn-primary inline-flex items-center gap-2 rounded-md px-4 py-2">
            <ArrowRight size={16} /> Ke PRD
          </Link>
        </div>
      </div>
    );
  }

  const isStreaming = isGenerating;

  return (
    <div className="flex h-dvh overflow-hidden bg-onyx text-(--text-primary)">
      {/* Left: TOC */}
      <aside
        style={{ width: `${leftWidth}px`, background: "var(--bg-page)" }}
        className={cn(
          "relative hidden h-full shrink-0 overflow-y-auto border-r border-(--color-graphite) bg-onyx p-4 md:block",
          !isDraggingLeft && "transition-[width] duration-300",
        )}
      >
        <TableOfContents content={acContent || ""} maxLevel={2} />
        <div
          className="absolute right-[-4px] top-0 z-10 h-full w-2 cursor-col-resize transition-colors hover:bg-indigo/20"
          onMouseDown={onStartDragLeft}
        />
      </aside>

      {/* Center */}
      <div className="flex min-w-0 flex-1 flex-col overflow-hidden" style={{ background: "var(--bg-page)" }}>
        {/* Topbar */}
        <div className="flex shrink-0 items-center border-b border-(--color-graphite) bg-obsidian px-4 py-3">
          <h1 className="truncate font-(--font-inter) text-lg font-[510] text-(--text-primary)">AC — {projectName}</h1>
        </div>

        {/* AC Viewer */}
        <div className="flex-1 overflow-hidden">
          <AcViewer
            content={acContent}
            streamingContent={streamingContent}
            isStreaming={isStreaming}
            hasError={hasError}
            projectName={projectName}
            plan={plan}
            className=""
          />
        </div>
      </div>
    </div>
  );
}