"use client";

import { ArrowRight, FileText, X } from "lucide-react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useCallback, useEffect, useRef, useState } from "react";
import { syncPaymentStatus } from "@/app/actions/payment";
import { CreditExhaustedModal } from "@/components/chat/credit-exhausted-modal";
import { consumeResumeIntent, consumeSuppressAutoGen } from "@/lib/prompt-handoff";
import { TableOfContents } from "@/components/prd/table-of-contents";
import { usePanelResize } from "@/hooks/use-panel-resize";
import { cn } from "@/lib/utils";
import { useChatStore, useUIStore } from "@/store";
import type { AcVersion, Plan } from "@/types/database";
import { AcViewer } from "./ac-viewer";

interface AcDetailProps {
	projectId: string;
	projectName: string;
	latestAcVersion?: AcVersion;
	latestPrdContent?: string;
	plan?: Plan;
}

export function AcDetail({
	projectId,
	projectName,
	latestAcVersion,
	latestPrdContent,
	plan = "free",
}: AcDetailProps) {
	const router = useRouter();
	const showToast = useUIStore((s) => s.showToast);
	const setGeneratingAC = useChatStore((s) => s.setGeneratingAC);
	const creditsExhausted = useChatStore((s) => s.creditsExhausted);
	const setCreditsExhausted = useChatStore((s) => s.setCreditsExhausted);
	const { leftWidth, onStartDragLeft, isDraggingLeft } = usePanelResize();
	const searchParams = useSearchParams();

	const [isGenerating, setIsGenerating] = useState(false);
	const [streamingContent, setStreamingContent] = useState<string>("");
	const [thinkingText, setThinkingText] = useState("");
	const [hasError, setHasError] = useState(false);
	const [saveFailed, setSaveFailed] = useState(false);
	const [isRetrySaving, setIsRetrySaving] = useState(false);
	const hasAutoGenerated = useRef(false);
	const abortRef = useRef<AbortController | null>(null);
	const contentRef = useRef("");

	const acContent = latestAcVersion?.content || null;

	const handleRetrySave = useCallback(async () => {
		setIsRetrySaving(true);
		try {
			const response = await fetch("/api/ac/save", {
				method: "POST",
				headers: { "Content-Type": "application/json" },
				body: JSON.stringify({ projectId, content: contentRef.current }),
			});
			const data = await response.json();
			if (!response.ok) throw new Error(data.error || "Gagal menyimpan AC");
			setSaveFailed(false);
			setHasError(false);
			router.refresh();
			showToast("AC berhasil disimpan!", "success");
		} catch (error: unknown) {
			showToast(
				error instanceof Error ? error.message : "Gagal menyimpan AC",
				"error",
			);
		} finally {
			setIsRetrySaving(false);
		}
	}, [projectId, showToast, router]);

	const handleGenerate = useCallback(async () => {
		if (!latestPrdContent) {
			showToast("PRD belum tersedia. Generate PRD terlebih dahulu.", "error");
			return;
		}
		setIsGenerating(true);
		setGeneratingAC(true);
		setStreamingContent("");
		contentRef.current = "";
		setHasError(false);
		setSaveFailed(false);

		abortRef.current?.abort();
		const controller = new AbortController();
		abortRef.current = controller;

		try {
			const response = await fetch("/api/ac/generate", {
				method: "POST",
				headers: { "Content-Type": "application/json" },
				body: JSON.stringify({
					projectId,
					model: sessionStorage.getItem("novaplan:selected-model") || undefined,
				}),
				signal: controller.signal,
			});
			if (!response.ok) {
				const error = await response.json();
				if (response.status === 403) {
					if (error.code === "UPGRADE_REQUIRED") {
						showToast("Generate AC hanya tersedia di paket Pro dan Hengker.", "error");
					} else {
						setCreditsExhausted({ stage: "ac", message: error.error || "Kredit habis." });
					}
					setIsGenerating(false);
					setGeneratingAC(false);
					return;
				}
				throw new Error(error.error || "Failed to generate AC");
			}
			const reader = response.body?.getReader();
			if (!reader) throw new Error("No reader available");
			const decoder = new TextDecoder();
			let buffer = "";
			let receivedTerminalEvent = false;
			while (true) {
				const { done, value } = await reader.read();
				if (done) break;
				buffer += decoder.decode(value, { stream: true });
				const lines = buffer.split("\n");
				buffer = lines.pop() || "";
				for (const line of lines) {
					if (line.startsWith("data: ")) {
						try {
							const data = JSON.parse(line.slice(6));
							if (data.type === "thinking") {
								setThinkingText((prev) => prev + data.content);
							} else if (data.type === "delta") {
								if (thinkingText) setThinkingText("");
								contentRef.current += data.content;
								setStreamingContent((prev) => prev + data.content);
							} else if (data.type === "done") {
								receivedTerminalEvent = true;
								router.refresh();
								showToast(
									"Acceptance Criteria berhasil digenerate!",
									"success",
								);
								setIsGenerating(false);
								setGeneratingAC(false);
							} else if (data.type === "error") {
								receivedTerminalEvent = true;
								setIsGenerating(false);
								setGeneratingAC(false);
								// Content already streamed but the DB save (Phase 2) failed - offer
								// recovery instead of the generic error state (PRD US-2, AC-2.1/2.2).
								if (contentRef.current.length > 0) {
									setSaveFailed(true);
								} else {
									setHasError(true);
								}
								showToast(data.error || "Gagal generate AC", "error");
							}
						} catch {
							/* skip malformed SSE line */
						}
					}
				}
			}
			// Stream closed without a done/error event (connection dropped mid-stream) -
			// content is silently truncated, so surface it instead of leaving no signal.
			if (!receivedTerminalEvent) {
				if (contentRef.current.length > 0) setSaveFailed(true);
				else setHasError(true);
			}
			setIsGenerating(false);
			setGeneratingAC(false);
		} catch (error: unknown) {
			const isAbort =
				(error instanceof DOMException || error instanceof Error) &&
				error.name === "AbortError";
			if (isAbort) {
				// A newer handleGenerate call already superseded this one (see abortRef.current?.abort()
				// above) - that call owns isGenerating/error state now, so don't stomp on it.
				if (abortRef.current !== controller) return;
				showToast(
					"Generate AC dibatalkan (timeout). Klik Generate ulang.",
					"error",
				);
				setHasError(true);
				setIsGenerating(false);
				setGeneratingAC(false);
				return;
			}
			console.error("Generate AC error:", error);
			const msg = error instanceof Error ? error.message : "Gagal generate AC";
			showToast(msg, "error");
			setHasError(true);
			setIsGenerating(false);
			setGeneratingAC(false);
		}
	}, [projectId, latestPrdContent, showToast, router, setGeneratingAC]);

	// Auto-generate AC on first visit
	useEffect(() => {
		if (
			!latestPrdContent ||
			latestAcVersion ||
			hasAutoGenerated.current ||
			isGenerating
		)
			return;
		// Suppress auto-generate when navigating from History (user must click explicitly)
		if (consumeSuppressAutoGen(projectId)) return;
		hasAutoGenerated.current = true;
		handleGenerate();
		// ponytail: auto-gen once per mount; ref guard prevents re-run when handleGenerate ref changes
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, [latestPrdContent, latestAcVersion, handleGenerate, projectId]);

	// Auto-resume AC generation after payment return
	useEffect(() => {
		const orderId = searchParams.get("order_id");
		const payment = searchParams.get("payment");
		if (!orderId || payment !== "success") return;
		(async () => {
			try {
				const res = await syncPaymentStatus({ data: orderId });
				if (!res.success) return;
				const resumedStage = consumeResumeIntent(projectId);
				if (resumedStage === "ac") {
					hasAutoGenerated.current = true;
					handleGenerate();
				}
				window.history.replaceState({}, "", window.location.pathname);
			} catch (e) {
				console.error("Auto-resume payment sync failed:", e);
			}
		})();
	}, [searchParams]);

	// Abort in-flight generation on unmount/project switch only - kept as a
	// separate effect (not the trigger effect's cleanup). Also resets
	// hasAutoGenerated so StrictMode's dev-mode phantom unmount->remount cycle
	// retries the aborted fetch instead of leaving it dead (the ref survives
	// the phantom cycle and would otherwise permanently block the retry).
	useEffect(() => {
		return () => {
			abortRef.current?.abort();
			hasAutoGenerated.current = false;
			setGeneratingAC(false);
			// Project switch may reuse this component instance - clear stale save-failure
			// state so a recovery banner/content from the previous project can't leak in.
			setSaveFailed(false);
			setHasError(false);
			setStreamingContent("");
			contentRef.current = "";
		};
	}, [projectId, setGeneratingAC]);

	if (!latestPrdContent) {
		return (
			<div className="flex h-dvh items-center justify-center bg-onyx text-(--text-primary)">
				<div className="text-center">
					<FileText
						size={64}
						className="mx-auto mb-4 text-(--text-secondary)"
					/>
					<h2 className="mb-2 text-xl font-[510] text-(--text-primary)">
						PRD Belum Tersedia
					</h2>
					<p className="mb-6 text-(--text-secondary)">
						Generate PRD terlebih dahulu sebelum membuat Acceptance Criteria.
					</p>
					<Link
						href={`/prd/${projectId}`}
						className="btn-primary inline-flex items-center gap-2 rounded-md px-4 py-2"
					>
						<ArrowRight size={16} /> Ke PRD
					</Link>
				</div>
			</div>
		);
	}

	const isStreaming = isGenerating;

	return (
		<>
		<div className="flex h-dvh flex-col overflow-hidden bg-onyx text-(--text-primary)">
			<div className="flex flex-1 overflow-hidden">
				{/* Left: TOC */}
				<aside
					style={{ width: `${leftWidth}px`, background: "var(--bg-page)" }}
					className={cn(
						"relative hidden h-full shrink-0 overflow-y-auto overflow-x-hidden border-r border-(--color-graphite) bg-onyx p-4 md:block",
						!isDraggingLeft && "transition-[width] duration-300",
					)}
				>
					<TableOfContents
						content={isStreaming ? streamingContent : acContent || ""}
						maxLevel={2}
					/>
					<div
						className="absolute right-[-4px] top-0 z-10 h-full w-2 cursor-col-resize transition-colors hover:bg-indigo/20"
						onMouseDown={onStartDragLeft}
					/>
				</aside>

				{/* Center Document View */}
				<div
					className={cn("flex min-w-0 flex-1 flex-col overflow-hidden")}
					style={{ background: "var(--bg-page)" }}
				>
					{/* Topbar */}
					<div className="flex shrink-0 items-center border-b border-(--color-graphite) bg-obsidian px-4 py-3">
						<h1 className="truncate font-(--font-inter) text-lg font-[510] text-(--text-primary)">
							AC - {projectName}
						</h1>
					</div>

					{saveFailed && (
						<div
							role="alert"
							className="flex shrink-0 flex-wrap items-center gap-3 border-b border-(--color-graphite) bg-amber-500/10 px-4 py-3 text-sm"
						>
							<span className="text-amber-500">
								AC berhasil digenerate tetapi gagal disimpan karena masalah
								koneksi database.
							</span>
							<button
								onClick={handleRetrySave}
								disabled={isRetrySaving}
								className="rounded-md bg-amber-500 px-3 py-1.5 font-[510] text-black transition-opacity hover:opacity-90 disabled:opacity-50"
							>
								{isRetrySaving ? "Menyimpan..." : "Retry Simpan (Tanpa AI)"}
							</button>
							<button
								onClick={handleGenerate}
								disabled={isRetrySaving}
								className="rounded-md border border-(--color-graphite) px-3 py-1.5 text-(--text-secondary) transition-colors hover:bg-white/5 disabled:opacity-50"
							>
								Generate Ulang
							</button>
						</div>
					)}

					{/* AC Viewer */}
					<div className="flex-1 overflow-hidden">
						{isGenerating && thinkingText && !streamingContent && (
							<details className="text-xs text-fog/60 mb-2 px-4" open>
								<summary className="cursor-pointer select-none">
									AI sedang berpikir...
								</summary>
								<pre className="mt-1 whitespace-pre-wrap text-xs text-fog/40 max-h-40 overflow-y-auto custom-scrollbar">
									{thinkingText}
								</pre>
							</details>
						)}
						<AcViewer
							content={acContent}
							streamingContent={streamingContent}
							isStreaming={isStreaming}
							hasError={hasError}
							projectName={projectName}
							plan={plan}
							className=""
						/>
					</div>
				</div>
			</div>
		</div>

		<CreditExhaustedModal
			isOpen={creditsExhausted?.stage === "ac"}
			onClose={() => setCreditsExhausted(null)}
			errorMessage={creditsExhausted?.message || ""}
			projectId={projectId}
			stage="ac"
			currentPlan={plan}
		/>
		</>
	);
}
